### ISSUE TITLE
Please use this week to redesign your homepage

### ISSUE THREAD

**Issue by jelkner** [Bbelboo/website#8]
The goal for your [homepage](https://bbelboo.github.io/website/) is to make it the gateway to your [digital portfolio](https://en.wikipedia.org/wiki/Electronic_portfolio).  Please use this week to work toward that end.  In particular, you should:

1. Move the birthday list to another pages that is linked from the homepage.
2. Tell us whose page we are viewing.
3. Provide links to your latest and best work.

You can begin to remove pages you made way back in the Fall, since you skills are so much better now.  Talk to me in class if you have more questions about what I'm asking, but I hope this points you in the right direction.

**Comment by Bbelboo** [comment]
Thanks, it does. I’ll work towards these goals this week. I really appreciate your feedback.

**Comment by Bbelboo** [comment]
I've redesigned my homepage and will thus close this issue.
